### PR TITLE
scd95_internal_scenario: Add new scenario files.

### PR DESCRIPTION
**Pull request by sahlman-nasa**
Add new scenario files for testing SCD0095 in the case where there is no priority and only one USS is used.

### CODE REVIEW

**Comment by sahlman-nasa** [comment]
Let me know what you think of this approach. I'm not convinced that simply planning a rejected OI will cause a conflict notification. 

If not, I'm curious about two things.

First, would I need to create an OI in the Nonconforming or Contingent state to create a conflict under the "no priority" condition?

Second, can the first created flight in this scenario be in the Accepted state to receive a notification, or does it need to transition to Activated?

**Comment by BenjaminPelletier** [comment]
I think it's valuable to have an example of the full details of a flow in #13 especially since it's first-of-kind, but I don't think we'd want to try to create a full sequence diagram for each scenario.  Once we're past the [design doc phase](https://github.com/interuss/tsc/blob/main/repo_contributions.md#create-or-update-design-doc), it should be possible to make most changes through multiple [small and focused PRs](https://github.com/interuss/tsc/blob/main/repo_contributions.md#general-principles).  A design doc is meant to be a top-level draft plan to provide context on how the overarching change will evolve over many PRs so that each PR can be evaluated more effectively with that broader context.  Developing the details should be done in the PRs themselves rather than the design doc because 1) details may need to evolve as practical considerations are discovered during the course of development and 2) we don't want to have to maintain documentation of fine details of the implementation nor let that documentation drift out of sync from the implementation itself.

The permanent [scenario documentation](https://github.com/interuss/monitoring/blob/main/CONTRIBUTING.md#scenario-documentation) is intended to be the interface between consumers of automated testing (regulators, USSs under test) and developers of automated testing (InterUSS contributors).  It should be minimal but clear so as to maximize readability by readers that often have less technical expertise, especially regulators, while still providing a sufficient explanation to the reader as to generally what is happening and how those actions validate compliance to requirements.  I don't think these sequence diagrams address that audience effectively as they have too much technical detail for someone who just wants to understand basically what is being done to validate requirements, but too little technical detail to fully define behavior (rather, that will come in the form of well-documented code).

So, I'd suggest we use #13 as a broad contextual overview to support then jumping directly into [iterative development](https://github.com/interuss/tsc/blob/main/repo_contributions.md#contributing-procedure) via small PRs.  Basically, let's go and start booking progress on [scenario development](https://github.com/interuss/monitoring/blob/main/CONTRIBUTING.md#uss_qualifier-test-scenarios) 100 (or even fewer!) lines at a time, and that's where we can develop and discuss the full details.

**Comment by sahlman-nasa** [comment]
Since we determined that a completed successful injection of a new or modified flight is necessary to cause a conflict and trigger the notification required for SCD0095, and in an equal priority no conflict environment, this cannot happen for unsuccessfully planned flights or even between two Accepted and/or Activated flights. However, if the USS-under-test is performing the CMSA role, then conflicts can be created with Nonconforming and Contingent flights. This scenario diagram uses a Nonconforming flight to create a conflict that could be tested in an equal priority no conflict environment.

**Comment by sahlman-nasa** [comment]
Even if this isn't a useful for the upcoming Key Site event we would still like to get some feedback/suggestions on this method for testing SCD0095. This is the approach that we are taking to ensure that each of the requirements in ASTM F3548-21 is addressed. Thanks!

**Comment by BenjaminPelletier** [comment]
I believe this work has been abandoned, but please feel free to reopen this PR if/when it is ready to continue.

**Pull request closed without merging**
