### PR TITLE
scd95_external_scenario: Add new scenario files.

### PR DESCRIPTION
**Pull request by sahlman-nasa**
Add new scenario to test SCD0095 for the case where there is no priority, and two USSs are involved.

### CODE REVIEW

**Comment by sahlman-nasa** [comment]
Note that I included interactions with the DSS and between USSs when I thought it was relevant, but not for every interaction. I thought this would keep the diagram from getting too cluttered, while still showing the interesting interactions. You can let me know if this is adequate.

**Comment by sahlman-nasa** [comment]
Added minor changes to conform more closely with MD file conventions. Also changed title to reflect that this is dependent on a Nonconforming flight and need not be restricted to an equal priority no conflict environment.

**Comment by sahlman-nasa** [comment]
Even if this isn't a useful for the upcoming Key Site event we would still like to get some feedback/suggestions on this method for testing SCD0095. Thanks!

**Comment by BenjaminPelletier** [comment]
I believe this work has been abandoned, but please feel free to reopen this PR if/when it is ready to continue.

**Pull request closed without merging**
